### ISSUE TITLE
Unraid Boinc Container Intel /dev/dri Issue

### ISSUE THREAD

**Issue by GoldenEye22** [linuxserver/docker-boinc#10]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

using the boinc app on unraid, everytime the app updates I get the intel gpu /dev/dri added back in and the application cannot execute. Is there some path I can put in there for those of us without intel? Otherwise I have to go and remove in manually after every update it seems
------------------------------

## Expected Behavior

An update doesn't cause the intel /dev/dri to return and breaks Boinc container in Unraid
## Current Behavior

Boinc container breaks every time I update because intel gpu /dev/dri is added back into container
## Steps to Reproduce

1. Boinc auto updated in Unriad
2. intel gpu /dev/dri section added back in
3. doesn't exist on my machine so container fails to execute
4. I have to edit and remove the /dev/dri to get cointainer to function again

## Environment
**OS:** UNRAID
**CPU architecture:** x86_64
**How docker service was installed:**

Installed through community applications on UNRAID and updated for my individual server setup
## Command used to create docker container (run/create/compose/screenshot)

lscr.io/linuxserver/boinc

**Comment by aptalca** [comment]
I know I said we'd fix it on discord but I realized we already mark it as not required in the template, so if it keeps getting added, it's an unRAID or CA issue and there's nothing we can do about it:
https://github.com/linuxserver/templates/blob/main/unraid/boinc.xml#L46

**Comment by GoldenEye22** [comment]
any path I can maybe can  put to have it work with it added

**Comment by aptalca** [comment]
you can edit the container settings in the unraid gui (advanced iirc) and remove the template url, which should stop the auto updates
