### ISSUE TITLE
Unable to run GPUGRID Python tasks, lacking bzip2

### ISSUE THREAD

**Issue by IanSteveC** [linuxserver/docker-boinc#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when trying to run GPUGRID Python GPU tasks (CUDA/Nvidia), the task fails in a few seconds. this seems to be because this image/container does not have bzip2 installed. these tasks use the boinc wrapper which calls the locally installed /bin/tar to extract a .bz2 archive.

error message given from the task stderr.txt
tar (child): lbzip2: Cannot exec: No such file or directory

### Expected Behavior

the archive should extract successfully and the task continue on as normal

### Steps To Reproduce

install this docker with nvidia CUDA 11.3+ drivers
pass an nvidia GPU into the container
add GPUGRID project
download GPUGRID python GPU tasks
attempt to run the task

it will fail to extract the archive

### Environment

```markdown
- OS: TrueNAS SCALE 22.12.0
- How docker service was installed: via TrueNAS Scale apps (TrueCharts)
```

### CPU architecture

x86-64

### Docker creation

```bash
N/A, automated via TrueCharts
```

### Container logs

```bash
N/A
```

**Comment by aptalca** [comment]
Sorry, just saw this.

We'll add bzip2

**Comment by IanSteveC** [comment]
> Sorry, just saw this.
> 
> We'll add bzip2

Thank you!
