### ISSUE TITLE
Instructions to setup reverse proxy

### ISSUE THREAD

**Issue by glensc** [linuxserver/docker-boinc#6]
I'm using this container via a reverse proxy, and can't have the application under root url.

here's my configuration for lighttpd:

```
$HTTP["url"] =~ "^/boinc/" {
        proxy.server = ( "" => ( (
                "host" => "127.0.0.1",
                "port" => "8080",
         ) ) )

        proxy.header = (
                "map-urlpath" => (
                        "/boinc/"  => "/",
                ),
                "upgrade" => "enable",
        )
}
```

docs: https://redmine.lighttpd.net/projects/lighttpd/wiki/Docs_ModProxy

**Comment by aptalca** [comment]
That's beyond the scope of this project. But if it helps, this image is using guacamole for the web interface. So look for a proxy config for guacamole. We're provide a proxy conf for our letsencrypt image here: https://github.com/linuxserver/reverse-proxy-confs/blob/master/boinc.subdomain.conf.sample

**Comment by glensc** [comment]
Perhaps add that info for standard readme where to look for reverse proxy configs?
