### ISSUE TITLE
Support Virtualbox

### ISSUE THREAD

**Issue by lunik1** [linuxserver/docker-boinc#8]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

Currently this container, unlike [the official BOINC client container](https://hub.docker.com/r/boinc/client), does not support projects/work units that require Virtualbox. It is possible to enable support by installing `virtualbox` in the container, allowing access to the `/dev/vboxdrv` device, and installing the appropriate drivers on the host system (as more or less described by the official container's documentation).

Is there any interest in supporting Virtualbox in this container?

## Alternatives Considered

As stated the official BOINC container supports Virtualbox, but not some of the other niceties that come with this container (guacamole, parameters, etc.).

This may be a more appropriate feature to include as a docker mod as Virtualbox is a fairly heavy dependency not all users will require.

**Comment by aptalca** [comment]
Docker mod would be more appropriate due to the heavy dependencies that are not necessary for the great majority of users.

Although personally I'm not familiar with what use case calls for running this in virtualbox and that's pretty much why I ignored it.

**Comment by lunik1** [comment]
There's a list of projects here https://boinc.berkeley.edu/projects.php supporting Virtualbox - only six in all so I agree that most users will not need it. Personally, I have received Virtualbox work from LHC@Home and Cosmology@Home. I think the use case is so projects can create reproducible, encapsulated environments to perform work in (and when BOINC was designed docker hadn't been invented yet 😃). I will look into converting my custom init script into a fully-fledged docker mod (should be trivial).

**Comment by lunik1** [comment]
I did put together a working mod at [lunik1/lsio-boinc-mod-virtualbox](https://github.com/lunik1/lsio-boinc-mod-virtualbox), however I ran into an issue on hosts where there is a mismatch in the VirtualBox versions between the host and the container. I replicated this issue on the official container and reported it at BOINC/boinc-client-docker#86 where it's awaiting for feedback.

**Comment by lunik1** [comment]
Looks like there is nothing to be done when it comes to mismatching VirtualBox versions. This makes VirtualBox support of limited usefulness to most users and a bit of a minefield, so I'm closing. Hopefully anybody who does need it will find this issue!

For those future users: I did make a (at time of writing) working mod at https://github.com/lunik1/lsio-boinc-mod-virtualbox but make sure you've read this thread so you understand its limitations!
